<script setup lang="ts">
import { ElMessage, ElMessageBox } from "element-plus";
import { computed, onMounted, ref } from "vue";
import { api, type ProviderModelProfile, type ProviderProfile } from "@/api/client";

const profiles = ref<ProviderProfile[]>([]);
const models = ref<Record<number, ProviderModelProfile[]>>({});
const loading = ref(false); const busy = ref(false); const json = ref(""); const parseError = ref("");
const templates: Record<string, object> = {
  fake: { display_name:"模拟 HTTP 服务商",provider_key:"fake-http",adapter:"FAKE",base_url:"http://127.0.0.1:8091/fake/v1",secret_env:"",models:[{model_key:"fake-image",remote_model:"fake-image",display_name:"模拟图片模型",type:"IMAGE",enabled:true},{model_key:"fake-video",remote_model:"fake-video",display_name:"模拟视频模型",type:"VIDEO",enabled:true}] },
  toapis: { display_name:"TOAPIS",provider_key:"toapis",adapter:"TOAPIS",base_url:"https://toapis.com/v1",secret_env:"TOAPIS_API_KEY",models:[{model_key:"seedream-5",remote_model:"doubao-seedream-5-0",display_name:"Seedream 5.0",type:"IMAGE",enabled:true},{model_key:"vidu-q3-pro",remote_model:"viduq3-pro",display_name:"Vidu Q3 Pro",type:"VIDEO",enabled:true}] },
  custom: { display_name:"自定义兼容服务商",provider_key:"custom",adapter:"MAPPED_ASYNC_HTTP",base_url:"https://example.invalid/v1",secret_env:"CUSTOM_PROVIDER_API_KEY",models:[] },
};
const preview = computed(() => { try { const value=JSON.parse(json.value); parseError.value=""; return value as Record<string,unknown>; } catch { parseError.value=json.value.trim()?"JSON 格式不正确。":""; return null; } });
onMounted(load);
async function load(){loading.value=true;try{profiles.value=await api.listProviderProfiles();await Promise.all(profiles.value.map(async p=>models.value[p.id]=await api.listProviderModels(p.id)));}finally{loading.value=false}}
function useTemplate(key:string){json.value=JSON.stringify(templates[key],null,2)}
async function importConfig(){if(!preview.value)return;busy.value=true;try{await api.importProviderConfig(preview.value);ElMessage.success("服务商配置已导入。");json.value="";await load()}catch(e){ElMessage.error(e instanceof Error?e.message:"导入失败")}finally{busy.value=false}}
async function toggle(p:ProviderProfile){await api.updateProviderProfile(p.id,{enabled:!p.enabled});await load()}
async function syncModels(p:ProviderProfile){busy.value=true;try{const result=await api.syncProviderModels(p.id,{confirm:false});if(!result.supported){ElMessage.warning(result.message);return}const names=result.models.map(m=>`${m.display_name}（${m.type==='IMAGE'?'图片':'视频'}）`).join("、");await ElMessageBox.confirm(`${result.message}\n${names}\n新模型默认停用。`,`同步 ${p.display_name||p.name} 模型`,{confirmButtonText:"确认保存",cancelButtonText:"取消"});await api.syncProviderModels(p.id,{confirm:true,models:result.models});ElMessage.success("模型同步结果已保存。");await load()}catch(e){if(e!=="cancel")ElMessage.error(e instanceof Error?e.message:"同步失败")}finally{busy.value=false}}
async function removeProvider(p:ProviderProfile){try{await ElMessageBox.confirm("删除前会检查项目引用、活动任务和模型引用；不会删除历史任务或资产。","删除服务商配置",{type:"warning",confirmButtonText:"删除配置",cancelButtonText:"取消"});await api.deleteProviderConfig(p.id);ElMessage.success("服务商配置已删除。");await load()}catch(e){if(e!=="cancel")ElMessage.error(e instanceof Error?e.message:"删除失败")}}
function count(p:ProviderProfile,type:"IMAGE"|"VIDEO"){return (models.value[p.id]??[]).filter(m=>m.generation_type===type).length}
</script>

<template><main class="page" v-loading="loading"><header><div><h1>服务商设置</h1><p>导入服务商配置，并管理可用于图片和视频生成的模型。</p></div><RouterLink to="/">返回项目</RouterLink></header>
<el-card class="import-card"><template #header><strong>导入服务商配置</strong></template><div class="templates"><span>使用内置模板：</span><el-button @click="useTemplate('fake')">模拟服务商</el-button><el-button @click="useTemplate('toapis')">TOAPIS</el-button><el-button @click="useTemplate('custom')">自定义兼容服务商</el-button></div><el-input v-model="json" type="textarea" :rows="9" placeholder="粘贴 JSON 配置；只能填写 secret_env 名称，不能包含真实密钥。"/><p v-if="parseError" class="error">{{parseError}}</p><div v-if="preview" class="summary"><strong>{{preview.display_name}}</strong><span>服务商标识：{{preview.provider_key}}</span><span>将导入 {{Array.isArray(preview.models)?preview.models.length:0}} 个模型</span></div><el-button type="primary" :disabled="!preview" :loading="busy" @click="importConfig">确认导入</el-button></el-card>
<h2>已配置服务商</h2><section class="cards"><el-card v-for="p in profiles" :key="p.id"><template #header><div class="title"><strong>{{p.display_name||p.name}}</strong><el-tag :type="p.enabled?'success':'info'">{{p.enabled?'已启用':'已停用'}}</el-tag></div></template><dl><dt>类型</dt><dd>{{p.adapter_type}}</dd><dt>图片模型</dt><dd>{{count(p,'IMAGE')}}</dd><dt>视频模型</dt><dd>{{count(p,'VIDEO')}}</dd><dt>密钥</dt><dd>{{p.adapter_type==='FAKE'?'无需密钥':p.secret_configured?'已配置':'未配置'}}</dd></dl><el-collapse><el-collapse-item title="查看模型"><p v-for="m in models[p.id]" :key="m.id">{{m.display_name}} · {{m.remote_model||m.model_key}} · {{m.generation_type==='IMAGE'?'图片模型':'视频模型'}} · {{m.enabled?'已启用':'已停用'}}</p></el-collapse-item><el-collapse-item title="高级诊断"><p>服务商标识：{{p.provider_key}}</p><p>适配器：{{p.adapter_type}}</p><p>基础 URL：{{p.base_url}}</p><p>配置版本：{{p.config_revision}}</p></el-collapse-item></el-collapse><div class="actions"><el-button @click="toggle(p)">{{p.enabled?'停用':'启用'}}</el-button><el-button :loading="busy" @click="syncModels(p)">同步模型</el-button><el-button type="danger" plain @click="removeProvider(p)">删除配置</el-button></div></el-card></section></main></template>
<style scoped>.page{padding:clamp(16px,3vw,36px);max-width:1280px;margin:auto}header,.title,.templates,.summary,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.import-card{margin:24px 0}.templates,.actions{justify-content:flex-start;margin-bottom:12px}.summary{justify-content:flex-start;padding:12px 0;color:var(--el-text-color-secondary)}.error{color:var(--el-color-danger)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}dl{display:grid;grid-template-columns:auto 1fr;gap:8px}dd{margin:0;text-align:right}</style>
