<script setup lang="ts">
import { DocumentAdd, Refresh, Upload } from "@element-plus/icons-vue";
import { ElMessage } from "element-plus";
import { computed, onMounted, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { api, type ScriptDocument, type ScriptSourceType } from "@/api/client";
import ProjectWorkspaceNav from "@/components/ProjectWorkspaceNav.vue";

const route=useRoute(); const router=useRouter(); const projectId=computed(()=>Number(route.params.projectId));
const loading=ref(false); const busy=ref(false); const fileInput=ref<HTMLInputElement|null>(null); const scripts=ref<ScriptDocument[]>([]);
const pasteForm=reactive({title:"",text:"",source_type:"PASTED" as ScriptSourceType});
onMounted(loadScripts);
async function loadScripts(){loading.value=true;try{scripts.value=await api.listScripts(projectId.value)}catch(e){ElMessage.error(e instanceof Error?e.message:"脚本加载失败")}finally{loading.value=false}}
async function importPaste(){if(!pasteForm.text.trim())return;await run(async()=>{const script=await api.importScriptText(projectId.value,{...pasteForm});pasteForm.title="";pasteForm.text="";await router.push(`/projects/${projectId.value}/scripts/${script.id}`)})}
async function importFile(event:Event){const target=event.target as HTMLInputElement;const file=target.files?.[0];if(!file)return;await run(async()=>{const script=await api.importScriptFile(projectId.value,file);await router.push(`/projects/${projectId.value}/scripts/${script.id}`)});target.value=""}
async function archiveScript(script:ScriptDocument){await run(async()=>{await api.archiveScript(script.id);await loadScripts()})}
async function run(action:()=>Promise<void>){busy.value=true;try{await action()}catch(e){ElMessage.error(e instanceof Error?e.message:"脚本操作失败")}finally{busy.value=false}}
</script>

<template><main class="page"><ProjectWorkspaceNav :project-id="projectId"/><header class="toolbar"><div><h1>脚本与分镜</h1><p>导入脚本，检查确定性解析结果，再将选中的镜头草稿应用到项目。</p></div><div class="toolbar-actions"><el-button :icon="Refresh" :loading="loading" @click="loadScripts">刷新</el-button><el-button :icon="Upload" :loading="busy" @click="fileInput?.click()">上传文件</el-button><input ref="fileInput" class="hidden-input" type="file" accept=".txt,.md,.fountain,.docx" @change="importFile"/></div></header>
<section class="workspace"><aside class="panel import-panel"><h2>导入脚本</h2><label>脚本标题<el-input v-model="pasteForm.title" maxlength="160" placeholder="输入脚本标题"/></label><label>导入方式<el-select v-model="pasteForm.source_type"><el-option label="粘贴文本" value="PASTED"/><el-option label="纯文本" value="PLAIN_TEXT"/><el-option label="Markdown" value="MARKDOWN"/><el-option label="Fountain" value="FOUNTAIN"/></el-select></label><label>脚本文本<el-input v-model="pasteForm.text" type="textarea" :rows="13" placeholder="在此粘贴脚本文本"/></label><el-alert title="支持纯文本、Markdown、Fountain 和 DOCX。解析过程不会调用网络或模型。" type="info" :closable="false"/><el-button type="primary" :icon="DocumentAdd" :disabled="!pasteForm.text.trim()" :loading="busy" @click="importPaste">导入并解析</el-button></aside>
<section v-loading="loading" class="preview-panel"><el-empty v-if="!scripts.length" description="从脚本开始创建分镜"><template #description><div class="empty-copy"><h2>从脚本开始创建分镜</h2><p>粘贴文本或上传脚本文件，系统会解析场景、角色和镜头草稿。</p><ol><li>导入脚本</li><li>检查解析结果</li><li>调整镜头草稿</li><li>应用到项目</li></ol></div></template></el-empty><template v-else><header class="preview-header"><h2>已导入脚本</h2><span>共 {{scripts.length}} 个版本</span></header><article v-for="script in scripts" :key="script.id" class="script-card"><div><h3>{{script.title}}</h3><p>{{script.block_count}} 个文本块 · {{script.storyboard_count}} 个分镜草稿 · {{script.status}}</p><el-tag size="small">{{script.source_type}}</el-tag></div><div class="row-actions"><el-button type="primary" @click="router.push(`/projects/${projectId}/scripts/${script.id}`)">检查解析结果</el-button><el-button :disabled="script.status==='ARCHIVED'" @click="archiveScript(script)">归档</el-button></div></article></template></section></section></main></template>
<style scoped>.page{padding:clamp(16px,3vw,32px);max-width:1440px;margin:auto}.toolbar,.toolbar-actions,.preview-header,.script-card,.row-actions{display:flex;justify-content:space-between;align-items:center;gap:12px}.toolbar{margin-bottom:20px}.toolbar h1{margin:0 0 6px}.toolbar p,.script-card p,.empty-copy p{color:var(--el-text-color-secondary)}.workspace{display:grid;grid-template-columns:minmax(360px,410px) minmax(0,1fr);gap:18px}.panel,.preview-panel,.script-card{border:1px solid var(--el-border-color);border-radius:12px;background:var(--el-bg-color);padding:18px}.import-panel{display:grid;gap:14px;align-content:start}.import-panel label{display:grid;gap:7px;font-weight:600}.preview-panel{min-height:520px}.empty-copy{text-align:left;max-width:470px}.empty-copy ol{display:grid;gap:12px;padding-left:22px}.script-card{margin-bottom:12px}.script-card h3{margin:0}.hidden-input{display:none}@media(max-width:800px){.toolbar,.toolbar-actions,.script-card{align-items:stretch;flex-direction:column}.workspace{grid-template-columns:1fr}.preview-panel{min-height:340px}.row-actions{justify-content:flex-start}}</style>
